### PR TITLE
Module script support

### PR DESCRIPTION
**Pull request by kcheick**
- allow a module script file to be referenced by the Powershell TypeProvider

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Awesome! Thank you @kcheick 
Could you please add sample to documentation [here](https://github.com/fsprojects/FSharp.Management/blob/master/docs/content/PowerShellProvider.fsx)?

**Comment by kcheick** [comment]
Done

**Comment by sergey-tihon** [comment]
@kcheick  Thanks

@vasily-kirichenko @forki Could you please release it on NuGet and update site?
I have some troubles to compile PS TP on Win10 for .NET 4.0 ... :disappointed:

**Comment by vasily-kirichenko** [comment]
Will do.

**Comment by vasily-kirichenko** [comment]
```
  1) Building d:\github\FSharp.Management\FSharp.Management.Tests.sln failed with exitcode 1.
  2) FS3021: d:\github\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(9,11): Unexpected exception from provided
 type 'FSharp.Management.PowerShellProvider,Modules="Microsoft.PowerShell.Management;Microsoft.PowerShell.Core"' member 'GetMethods': The ty
pe provider 'FSharp.Management.PowerShellProvider.PowerShellProvider' reported an error: Could not create PowerShell Runspace: 'The type ini
tializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.'
  3) FS0039: d:\github\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(13,14): The field, constructor or member
'Get-Item' is not defined
  4) FS0072: d:\github\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(16,9): Lookup on object of indeterminate
type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of
the object. This may allow the lookup to be resolved.
  5) FS0039: d:\github\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(21,14): The field, constructor or member
'Get-Process' is not defined
  6) FS0039: d:\github\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(27,14): The field, constructor or member
'Get-PSSnapin' is not defined
  7) FS0072: d:\github\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(29,9): Lookup on object of indeterminate
type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of
the object. This may allow the lookup to be resolved.
  8) FS0039: d:\github\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(34,14): The field, constructor or member
'Get-Random' is not defined
  9) FS0039: d:\github\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(40,14): The field, constructor or member
'Get-EventLog' is not defined
 10) FS3021: d:\github\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(46,22): Unexpected exception from provide
d type 'FSharp.Management.PowerShellProvider,Modules="d:\\github\\FSharp.Management\\tests\\FSharp.Management.Tests\\testModule.psm1"' membe
r 'GetMethods': The type provider 'FSharp.Management.PowerShellProvider.PowerShellProvider' reported an error: Could not create PowerShell R
unspace: 'The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.'
 11) FS0039: d:\github\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(51,24): The field, constructor or member
'doSomething' is not defined
 12) FS3021: d:\github\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(59,13): Unexpected exception from provide
d type 'FSharp.Management.PowerShellProvider,Modules="Microsoft.PowerShell.Management;Microsoft.PowerShell.Core",Is64BitRequired="True"' mem
ber 'GetMethods': The type provider 'FSharp.Management.PowerShellProvider.PowerShellProvider' reported an error: Value cannot be null.↔Param
eter name: uri
 13) FS0039: d:\github\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(64,16): The field, constructor or member
'Get-Item' is not defined
....
```

**Comment by vasily-kirichenko** [comment]
If you confirm that the tests pass on your machine, I can comment them in the build script and release the package.

**Comment by sergey-tihon** [comment]
I see [passed tests on AppVeyor](https://ci.appveyor.com/project/sergey-tihon/fsharp-management-6aqlt/build/0.0.1.3#L255)
but we definitely should fix build on local machines ...

**Comment by sergey-tihon** [comment]
Issue: [Unable to use System.Management.Automation.dll assembly in a .NET 4.0 application on Windows 10](https://connect.microsoft.com/VisualStudio/feedback/details/1817986/unable-to-use-system-management-automation-dll-assembly-in-a-net-4-0-application-on-windows-10)

As workaround we can target PS TP projects and tests to .NET 4.5

@kcheick Do you know how to fix following error?
    

>d:\GitHub\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(46,22): error FS3021: Unexpected exception from provided type 'FSharp.Management.PowerShellProvider,Modules="d:\\GitHub\\FSharp.Management\\tests\\FSharp.Management.Tests\\testModule.psm1"' member 'GetMethods': The type provider 'FSharp.Management.PowerShellProvider.PowerShellProvider' reported an error: Could not create PowerShell Runspace: 'File D:\GitHub\FSharp.Management\tests\FSharp.Management.Tests\testModule.psm1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.' 
     d:\GitHub\FSharp.Management\tests\FSharp.Management.Tests\PowerShellProvider.Tests.fs(51,24): error FS0039: The field, constructor or member 'doSomething' is not defined 

I have tried
```powershell
set-executionpolicy remotesigned
```
but it did not help

**Comment by kcheick** [comment]
try with 

``` powershell 
set-executionpolicy unrestricted
```
that is how the script execution is configured on my system

**Comment by sergey-tihon** [comment]
The same error
image

**Comment by kcheick** [comment]
it turns out my machine was configured to be remotesigend after all
But i had to convert the project to .net 4.5 to be able to build them, i am using windows 10 )/
I can push those change too if you need

image

**Pull request merged**
